/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Created:		May 16, 2024
 *			Pratik Nag <nagp@peacock>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.12.0\n"
	"                  Configured on: Thu May 16 10:50:39 +03 2024\n"
	"                  Configured by: nagp@peacock\n"
	"                    Host system: x86_64-unknown-linux-gnu\n"
	"              Uname information: Linux peacock 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /home/nagp/exageostat-dev/dependinces_installations\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: debug\n"
	"              Debugging Symbols: yes\n"
	"                        Asserts: yes\n"
	"                      Profiling: no\n"
	"             Optimization Level: debug\n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: static, shared\n"
	"  Statically Linked Executables: \n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS:  -L/home/nagp/exageostat-dev/dependinces_installations/lib\n"
	"                Extra libraries: -lz -ldl -lm \n"
	"                       Archiver: ar\n"
	"                       AR_FLAGS: cr\n"
	"                         Ranlib: ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: /opt/ecrc/gcc/10.2.0/ub18/bin/gcc ( gcc (GCC) 10.2.0)\n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -UNDEBUG -DH5AC_DEBUG -DH5B2_DEBUG -DH5CX_DEBUG -DH5D_DEBUG -DH5F_DEBUG -DH5HL_DEBUG -DH5I_DEBUG -DH5O_DEBUG -DH5S_DEBUG -DH5ST_DEBUG -DH5T_DEBUG -DH5Z_DEBUG -DH5_DEBUG_API\n"
	"                    AM_CPPFLAGS:  -I/home/nagp/exageostat-dev/dependinces_installations/include\n"
	"                        C Flags: \n"
	"                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wno-c++-compat -Wno-format-nonliteral -Wshadow -Wundef -Wwrite-strings -pedantic -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wdisabled-optimization -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-enum -Wswitch-default -Wunused-macros -Wunsafe-loop-optimizations -Wlogical-op -Wlarger-than=2560 -Wsync-nand -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wstrict-overflow=5 -Wjump-misses-init -Wunsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wvector-operation-performance -Wdate-time -Warray-bounds=2 -Wc99-c11-compat -Wnull-dereference -Wunused-const-variable -Wduplicated-cond -Whsa -Wnormalized -Walloc-zero -Walloca -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough=5 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -ftrapv -fno-common -g -fno-omit-frame-pointer -Wno-aggregate-return -Wno-inline -Wno-missing-format-attribute -Wno-missing-noreturn -Wno-suggest-attribute=const -Wno-suggest-attribute=pure -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=format -Wno-suggest-attribute=cold -Wno-suggest-attribute=malloc -Og\n"
	"                     AM C Flags: \n"
	"               Shared C Library: yes\n"
	"               Static C Library: yes\n"
	"\n"
	"\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"                           Java: no\n"
	"\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                   Parallel HDF5: no\n"
	"Parallel Filtered Dataset Writes: no\n"
	"              Large Parallel I/O: no\n"
	"              High-level library: yes\n"
	"                Build HDF5 Tests: yes\n"
	"                Build HDF5 Tools: yes\n"
	"                    Threadsafety: no\n"
	"             Default API mapping: v112\n"
	"  With deprecated public symbols: yes\n"
	"          I/O filters (external): deflate(zlib)\n"
	"                             MPE: no\n"
	"                   Map (H5M) API: no\n"
	"                      Direct VFD: no\n"
	"              (Read-Only) S3 VFD: no\n"
	"            (Read-Only) HDFS VFD: no\n"
	"                         dmalloc: no\n"
	"  Packages w/ extra debug output: AC,B2,CX,D,F,HL,I,O,S,ST,T,Z\n"
	"                     API tracing: yes\n"
	"            Using memory checker: no\n"
	" Memory allocation sanity checks: yes\n"
	"          Function stack tracing: no\n"
	"       Strict file format checks: yes\n"
	"    Optimization instrumentation: no\n"
;

