image: registry.gitlab.inria.fr/solverstack/docker/distrib

Find:
  artifacts:
    name: find_ctests
    expire_in: 1 week
    paths:
     - build
    reports:
      junit: report.xml
  script:
    - modules/find/tests/run_ctest.sh
  after_script:
    - xsltproc -o report.xml /home/gitlab/ctest-to-junit.xsl build/Testing/**/Test.xml
